### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by lld1995** [BobLd/Caly#25]
![image](https://github.com/user-attachments/assets/c056a933-e0ae-4c4e-83bc-5d50ae5e90dd)

**Comment by BobLd** [comment]
Hi @lld1995 it seems to be a bug in PdfPig (and not Caly), can you share the pdf document?

**Comment by BobLd** [comment]
@lld1995 closing the issue as there is not much that can be done without the problematic pdf document. Feel free to re-open the issue if you can share it
