### ISSUE TITLE
should i fix the dependencies problem?

### ISSUE THREAD

**Issue by zkvii** [BobLd/Caly#7]
<img width="571" alt="image" src="https://github.com/BobLd/Caly/assets/113273091/243bc1c6-c8f6-4c62-b726-d9b4e3d3b8f9">

I also noticed that there is a significant difference between the PDFPig version and the official version. Should I use the latest one or stick with this one?
<img width="548" alt="image" src="https://github.com/BobLd/Caly/assets/113273091/7901a14a-3f76-4261-a48d-712397acc83b">

**Comment by BobLd** [comment]
@zkvii can you make sure you're using the `external` repos / submodules (not the NuGet packages) and run the following command after you clone the Caly repo?

```
git submodule update --init --recursive
```

**Comment by zkvii** [comment]
Yes, I am certain that I encountered the same errors on both my Mac and two Windows PCs. Additionally, if I replace it with NuGet packages, the preview version of pdfpig (0.1.9-alpha), the errors can be fixed. Then I noticed that there might be some differences in your forked pdfpig branch, although this is not a major issue, merging the code might require some work.
<img width="662" alt="image" src="https://github.com/BobLd/Caly/assets/113273091/dec7f7d3-245d-45d0-8fc6-9cb346af825e">

**Comment by BobLd** [comment]
okay thanks for that, Leave it to me then, I'll look into that shortly

**Comment by BobLd** [comment]
@zkvii can you pull the latest change from `master` run
```
git submodule update --init --recursive
```

and try running the app. You might have to unload Caly.iOS and Caly.Android

**Comment by zkvii** [comment]
> @zkvii can you pull the latest change from `master` run
> 
> ```
> git submodule update --init --recursive
> ```
> 
> and try running the app. You might have to unload Caly.iOS and Caly.Android

Now I can work normally, but I need to add `<Nullable>annotations< Nullable>` in all pdfpig dependencies.
